import { saveTemplate } from './storage';
import type { Template } from 'shared';

function uid() {
  try { return crypto.randomUUID(); } catch { return Math.random().toString(36).slice(2); }
}

const NOW = new Date().toISOString();

// Pre-generate IDs needed for cross-referencing in SWITCH conditions (template 5)
const LEKTIRA_SCIENCE_ID  = uid();
const LEKTIRA_ART_ID      = uid();
const LEKTIRA_MISSION_ID  = uid();
const LEKTIRA_SURVEY_ID   = uid();

export const SEED_TEMPLATES: Template[] = [
  // ─── 1. Синтетичка геометрија во реалниот простор ────────────────────────────
  {
    id: uid(),
    title: 'Синтетичка геометрија во реалниот простор',
    subject: 'Математика',
    grade: '8 одд.',
    description: 'Учениците наоѓаат агли и пресметуваат симетрали користејќи објекти во природата. Идеално за училишен двор или локален парк.',
    difficulty: 'средно',
    estimatedMinutes: 45,
    playMode: 'singleplayer',
    tags: ['геометрија', 'теренска', 'gps', 'симетрала'],
    stageCount: 5,
    rating: 4.8,
    ratingCount: 12,
    usageCount: 34,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: true,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Добредојдовте на геометриска авантура!',
        description: 'Денес ќе ги истражувате **геометриски форми во реалниот свет**. Ќе конструирате симетрали и ќе докажете дека секоја точка на симетрала е подеднакво оддалечена од краците на аголот.\n\n📐 Подготви: јаже, креда, линијар.\n\nПресретнуваме на GPS точка 1!',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 1, points: 50,
        title: 'Најди ја почетната точка',
        description: 'Оди до аголот кај влезот на зградата (или средиштето на дворот). Кога ќе се наоѓаш на 5 метри, доаѓаш до следниот чекор.',
        targetCoordinates: { latitude: 41.9981, longitude: 21.4254 },
        radiusMeters: 15,
        showMode: 'map',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'MISSION', order: 2, points: 100,
        title: 'Конструирај симетрала',
        description: 'Користејќи јаже или креда, конструирај ја симетралата на аголот кој го формираат две патеки/ѕидови пред тебе.\n\n📸 Сними фотографија од конструкцијата. Мора да се гледаат и двата крака на аголот и симетралата.',
        submissionType: 'photo',
      },
      {
        id: uid(), type: 'QUIZ', order: 3, points: 80,
        title: 'Доказ за симетрала',
        description: 'Земи две точки на различни краци на аголот, подеднакво оддалечени од темето. Измери ги нивните растојанија до симетралата. Колку се тие растојанија?',
        questionType: 'multiple_choice',
        options: ['Нееднакви', 'Подеднакви', 'Зависи од аголот', 'Не може да се измери'],
        correctAnswer: 'Подеднакви',
        hintText: 'Симетралата е "огледало" — секоја точка на неа е на исто растојание од двата крака.',
        requiredToAdvance: false,
        timeLimitSeconds: 60,
      },
      {
        id: uid(), type: 'SURVEY', order: 4, points: 20,
        title: 'Рефлексија',
        description: 'Размисли за денешната активност:',
        surveyQuestions: [
          'Кое беше најтешкото нешто при конструирањето на симетралата?',
          'Дали ти беше полесно да го разбереш концептот со практична вежба наместо на хартија? Зошто?',
          'Каде во секојдневниот живот среќаваш симетрали?',
        ],
      },
    ],
  },

  // ─── 2. Процентополис — QR Квест ─────────────────────────────────────────────
  {
    id: uid(),
    title: 'Процентополис — QR Авантура',
    subject: 'Математика',
    grade: '7 одд.',
    description: 'Мрежа од скриени QR кодови низ училиштето. Секој код активира задача за математичко моделирање и проценти.',
    difficulty: 'средно',
    estimatedMinutes: 50,
    playMode: 'singleplayer',
    tags: ['проценти', 'qr', 'моделирање', 'училиште'],
    stageCount: 6,
    rating: 4.9,
    ratingCount: 18,
    usageCount: 67,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: true,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Добредојдовте во Процентополис!',
        description: '🏙️ Градот Процентополис е полн со математички загатки скриени зад QR кодови.\n\nТвојата задача: Скенирај ги QR кодовите поставени низ училишниот ходник и реши ги задачите за проценти.\n\n**Правила:**\n- Скенирај секој QR код со камерата\n- Одговори точно за да ги освоиш поените\n- Времето е ограничено на 30 секунди по задача!',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'SCAN_CODE', order: 1, points: 50,
        title: 'QR Станица 1 — Влез во градот',
        description: 'Пронајди го QR кодот залепен на влезните врати или огласната табла. Скенирај го за да влезеш во Процентополис!',
        targetQrPayload: 'PROCESNTOPOLIS_STATION_1',
      },
      {
        id: uid(), type: 'QUIZ', order: 2, points: 100,
        title: 'Задача: Попуст во продавница',
        description: 'Кај влезот скенираш информација: **"Продавница нуди 25% попуст на цена од 1200 ден."**\n\nКолку денари изнесува попустот?',
        questionType: 'free_text',
        correctAnswer: '300',
        hintText: 'Процент × Основа ÷ 100 = ?',
        timeLimitSeconds: 30,
        requiredToAdvance: false,
      },
      {
        id: uid(), type: 'SCAN_CODE', order: 3, points: 50,
        title: 'QR Станица 2 — Банка на Процентополис',
        description: 'Пронајди го вториот QR код залепен кај скалите или во ходникот. Во банката чека нова задача!',
        targetQrPayload: 'PROCESNTOPOLIS_STATION_2',
      },
      {
        id: uid(), type: 'QUIZ', order: 4, points: 120,
        title: 'Задача: Банкарска камата',
        description: '🏦 Наклонот на скалите во банката е 35°. Стандардот за пристапност бара наклон **помал од 30°**.\n\nЗа колку проценти треба да се намали наклонот за да ги исполни стандардите?\n\nОдговори со број (без % знак).',
        questionType: 'estimate_number',
        correctAnswer: 5,
        hintText: 'Разлика = 35 - 30 = ? Изрази ја разликата во однос на 35.',
        timeLimitSeconds: 45,
        requiredToAdvance: false,
      },
      {
        id: uid(), type: 'MISSION', order: 5, points: 80,
        title: 'Финален доказ',
        description: '📸 Направи слика на некоја цена или процент кој го гледаш во или околу училиштето (огласна табла, книга, реклама).\n\nСнимката е твојот излез од Процентополис!',
        submissionType: 'photo',
      },
    ],
  },

  // ─── 3. Лов на екосистеми — Биологија ────────────────────────────────────────
  {
    id: uid(),
    title: 'Лов на екосистеми — Биологија',
    subject: 'Природни науки',
    grade: '6 одд.',
    description: 'Теренска настава. Учениците истражуваат локални екосистеми, фотографираат растенија и мерат податоци на терен.',
    difficulty: 'лесно',
    estimatedMinutes: 60,
    playMode: 'singleplayer',
    tags: ['биологија', 'екосистем', 'теренска', 'природа'],
    stageCount: 6,
    rating: 4.7,
    ratingCount: 9,
    usageCount: 28,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: false,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Денес сте истражувачи!',
        description: '🌿 Добредојдовте на теренска настава по биологија!\n\nДенес ќе ги истражувате **локалните екосистеми** — ќе фотографирате растенија, ќе набљудувате животни и ќе мерите услови на средина.\n\nПодгответе: фотоапарат (телефон), тетратка за набљудувања.\n\n**Бидете внимателни кон природата!** 🍃',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 1, points: 50,
        title: 'Точка 1: Влез во екосистемот',
        description: 'Одете до зеленото подрачје (парк, двор, природа). Овде почнува истражувањето.',
        targetCoordinates: { latitude: 41.9981, longitude: 21.4254 },
        radiusMeters: 20,
        showMode: 'map',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'MISSION', order: 2, points: 100,
        title: 'Фотографирај растение',
        description: '📸 Пронајди растение и направи детална слика.\n\nВо описот наведи:\n- Вид (ако го знаеш)\n- Каде расте (сенка/сонце, влажно/суво)\n- Дали гледаш некои животни или инсекти на него?',
        submissionType: 'photo',
      },
      {
        id: uid(), type: 'QUIZ', order: 3, points: 80,
        title: 'Кој е производител во екосистемот?',
        description: 'Врз основа на тоа што го гледаш наоколу — кој организам е **производител** (прима енергија директно од сонцето)?',
        questionType: 'multiple_choice',
        options: ['Трева и дрвја', 'Лисици и зајаци', 'Глувци и инсекти', 'Габи и бактерии'],
        correctAnswer: 'Трева и дрвја',
        hintText: 'Производителите прават храна преку фотосинтеза — потребно им е сонце!',
        requiredToAdvance: false,
        timeLimitSeconds: 45,
      },
      {
        id: uid(), type: 'MISSION', order: 4, points: 80,
        title: 'Измери ги условите',
        description: '🌡️ Измери ги следните параметри на местото каде се наоѓаш и напиши ги:\n\n- Приближна температура (°C)\n- Влажност (суво / умерено / влажно)\n- Осветленост (сенка / полусенка / директно сонце)\n\nСними аудио запис со твоите набљудувања.',
        submissionType: 'audio',
      },
      {
        id: uid(), type: 'SURVEY', order: 5, points: 20,
        title: 'Набљудувања на теренот',
        description: 'Запиши ги своите теренски набљудувања:',
        surveyQuestions: [
          'Колку различни видови растенија набројуваш (приближно)?',
          'Дали забележа некои животни или инсекти? Кои?',
          'Кои човечки активности ги гледаш кои влијаат на овој екосистем?',
          'Дали мислиш дека овој екосистем е здрав? Зошто?',
        ],
      },
    ],
  },

  // ─── 4. Дигитален Времеплов — Историја ───────────────────────────────────────
  {
    id: uid(),
    title: 'Дигитален Времеплов — Историја',
    subject: 'Историја',
    grade: '9 одд.',
    description: 'Рута низ градот до споменици со аудио-информации. Учениците снимаат видео репортажи како новинари од минатото.',
    difficulty: 'средно',
    estimatedMinutes: 75,
    playMode: 'singleplayer',
    tags: ['историја', 'grad', 'gps', 'споменици', 'новинарство'],
    stageCount: 5,
    rating: 5.0,
    ratingCount: 6,
    usageCount: 15,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: true,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Добредојдовте во Дигиталниот Времеплов!',
        description: '📡 Вие сте **новинари кои известуваат во живо** од историски настани!\n\nДенешната рута ве носи до важни историски места во градот. На секое место ќе добиете кратка историска информација, а потоа ќе снимите **видео репортажа** — глумете дека сте новинари кои известуваат директно од минатото!\n\n🎥 Подгответе камера. Историјата чека!',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 1, points: 50,
        title: 'Историска локација 1',
        description: 'Одете до прва историска точка во градот (централен плоштад или споменик). GPS ќе ве води.',
        targetCoordinates: { latitude: 41.9961, longitude: 21.4316 },
        radiusMeters: 25,
        showMode: 'map',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'MISSION', order: 2, points: 120,
        title: 'Репортажа 1: Историски настан',
        description: '🎙️ Снимете кратка **видео репортажа до 60 секунди** во која:\n\n1. Претставете се како новинар (измислено историско медиумско куќа)\n2. Опишете каде се наоѓате и кој историски настан се случил тука\n3. Кажете зошто е ова место важно за историјата на Македонија\n\nБидете креативни — историјата е жива!',
        submissionType: 'video',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 3, points: 50,
        title: 'Историска локација 2',
        description: 'Продолжете до втората историска точка. Нова приказна чека!',
        targetCoordinates: { latitude: 41.9970, longitude: 21.4283 },
        radiusMeters: 25,
        showMode: 'map',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'QUIZ', order: 4, points: 100,
        title: 'Историски факт — провери го знаењето',
        description: 'Врз основа на сè што научивте денес на теренот:\n\nКоја е улогата на **материјалното наследство** (споменици, градби) во зачувувањето на историската меморија?',
        questionType: 'multiple_choice',
        options: [
          'Служи само за туристички цели',
          'Ги поврзува генерациите и ја чува колективната меморија',
          'Нема практична вредност во модерно доба',
          'Важно е само за историчари',
        ],
        correctAnswer: 'Ги поврзува генерациите и ја чува колективната меморија',
        timeLimitSeconds: 60,
        requiredToAdvance: false,
      },
    ],
  },

  // ─── 5. Интерактивна Лектира — Storytelling со SWITCH ───────────────────────
  {
    id: uid(),
    title: 'Интерактивна Лектира — Раскажувај приказна!',
    subject: 'Јазици',
    grade: '7-9 одд.',
    description: 'Секоја станица е поглавје. Учениците одговараат на прашања и самите одлучуваат како завршува приказната преку логички разгранувања.',
    difficulty: 'лесно',
    estimatedMinutes: 40,
    playMode: 'singleplayer',
    tags: ['литература', 'storytelling', 'разгранување', 'лектира'],
    stageCount: 7,
    rating: 4.6,
    ratingCount: 14,
    usageCount: 42,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: false,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Поглавје 1: Почетокот',
        description: '📖 *Беше еднаш еден млад студент кој открил тајна библиотека скриена длабоко под градот...*\n\nВо библиотеката имало две врати:\n- **Лева врата**: водела до Сала на науките\n- **Десна врата**: водела до Сала на уметноста\n\nНо за да избере, прво морал да одговори на прашањата на чуварот...',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'QUIZ', order: 1, points: 80,
        title: 'Прашање на чуварот',
        description: 'Чуварот на библиотеката прашува:\n\n*"Која фигура на зборот се користи кога кажуваме: Времето лета?"*',
        questionType: 'multiple_choice',
        options: ['Метафора', 'Персонификација', 'Компарација', 'Хипербола'],
        correctAnswer: 'Метафора',
        hintText: 'Времето не може буквално да лета — претставуваме апстрактно преку конкретно.',
        timeLimitSeconds: 60,
        requiredToAdvance: false,
      },
      {
        id: uid(), type: 'SWITCH', order: 2, points: 0,
        title: 'Чуварот те насочува...',
        description: 'Врз основа на твоите поени, чуварот те насочува кон соодветната сала.',
        conditions: [
          {
            id: uid(),
            label: 'Точен одговор (≥80 поени) → Сала на науките',
            minPoints: 80,
            targetStageId: LEKTIRA_SCIENCE_ID,
          },
        ],
        defaultTargetStageId: LEKTIRA_ART_ID,
        showPathsToPlayer: false,
      },
      {
        id: LEKTIRA_SCIENCE_ID, type: 'INFO', order: 3, points: 0,
        title: 'Сала на науките',
        description: '🔬 *Студентот влегол во Сала на науките. Полиците беа полни со книги за физика, хемија и математика. На средниот стол лежела отворена книга со чудни равенки...*\n\nАко одговориш точно на следното прашање, ќе ја открие тајната на библиотеката!',
        mediaType: 'none',
      },
      {
        id: LEKTIRA_ART_ID, type: 'INFO', order: 4, points: 0,
        title: 'Сала на уметноста',
        description: '🎨 *Студентот влегол во Сала на уметноста. Ѕидовите беа покриени со слики и скулптури. На центарот стоела мистериозна статуа...*\n\nАко одговориш точно на следното прашање, ќе ја открие тајната на библиотеката!',
        mediaType: 'none',
      },
      {
        id: LEKTIRA_MISSION_ID, type: 'MISSION', order: 5, points: 100,
        title: 'Напиши го крајот на приказната',
        description: '✍️ Сега ТИ си авторот!\n\nНапиши краток крај на приказната за студентот (5-7 реченици). Вклучи:\n- Каква тајна открил?\n- Kako се чувствувал?\n- Дали се вратил повторно?\n\nСними аудио запис во кој ја читаш приказната со емоции.',
        submissionType: 'audio',
      },
      {
        id: LEKTIRA_SURVEY_ID, type: 'SURVEY', order: 6, points: 20,
        title: 'Рефлексија за приказната',
        description: 'Размисли за денешната активност:',
        surveyQuestions: [
          'Кој дел од приказната ти беше најинтересен и зошто?',
          'Дали сакаш да читаш книги со разгранување каде сам го бираш крајот?',
          'Кој книжевен лик (реален или измислен) би го поканил во оваа библиотека?',
        ],
      },
    ],
  },

  // ─── 6. Ориентационо трчање и здравје ────────────────────────────────────────
  {
    id: uid(),
    title: 'Ориентационо трчање и здравје',
    subject: 'Физичко',
    grade: 'Сите',
    description: 'Комбинира физичка активност и знаење. Спринт помеѓу GPS точки и одговарање на брз квиз за анатомија и здравје.',
    difficulty: 'лесно',
    estimatedMinutes: 35,
    playMode: 'singleplayer',
    tags: ['физичко', 'трчање', 'gps', 'здравје', 'анатомија'],
    stageCount: 7,
    rating: 4.5,
    ratingCount: 11,
    usageCount: 51,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: false,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Спремни, внимание, крени!',
        description: '🏃 Добредојдовте на **Ориентационото трчање**!\n\nПравила:\n1. Трчај до секоја GPS точка\n2. Кога ќе пристигнеш, одговори на брз квиз\n3. Помалку време = повеќе поени\n4. Нема правилен одговор за здравје — сите тела се различни!\n\n🎯 Цел: Движење + Знаење = Здравје!\n\nГотов? Поаѓај!',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 1, points: 50,
        title: '🏁 Точка 1: Загревање',
        description: 'Трчај до ознаката А (северен агол на теренот/дворот). Загрејте се!',
        targetCoordinates: { latitude: 41.9985, longitude: 21.4260 },
        radiusMeters: 10,
        showMode: 'arrow',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'QUIZ', order: 2, points: 100,
        title: 'Квиз: Срце и крвоток',
        description: '❤️ Брзо! Колку пати во минута чука срцето на здрав возрасен во мирување?',
        questionType: 'multiple_choice',
        options: ['20-40 пати', '60-100 пати', '120-160 пати', '160-200 пати'],
        correctAnswer: '60-100 пати',
        timeLimitSeconds: 20,
        requiredToAdvance: false,
        hintText: 'Пулсот е мерка за здравјето на срцето.',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 3, points: 50,
        title: '🏁 Точка 2: Спринт!',
        description: 'Спринт до ознаката Б (јужен агол)! Пресметај ги кардио поените!',
        targetCoordinates: { latitude: 41.9978, longitude: 21.4268 },
        radiusMeters: 10,
        showMode: 'arrow',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'QUIZ', order: 4, points: 100,
        title: 'Квиз: Мускули и коски',
        description: '💪 Колку коски има во човечкото тело на возрасен?',
        questionType: 'multiple_choice',
        options: ['106', '206', '306', '406'],
        correctAnswer: '206',
        timeLimitSeconds: 20,
        requiredToAdvance: false,
        hintText: 'Новородените имаат повеќе — со растење некои коски се спојуваат.',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 5, points: 50,
        title: '🏁 Точка 3: Финален спринт!',
        description: 'Последна точка — дај сè! Трчај до ознаката В (старт)!',
        targetCoordinates: { latitude: 41.9981, longitude: 21.4254 },
        radiusMeters: 10,
        showMode: 'arrow',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'TOURNAMENT', order: 6, points: 150,
        title: '🏆 Финален турнир: Класна битка!',
        description: 'Споредете ги резултатите со соучениците. Кој е најбрз ориентирист со најдобро знаење за здравје?\n\nЧеститки на сите учесници — движењето е победа!',
        teamCount: 4,
        taskDescription: 'Кој тим освоил највеќе поени вкупно?',
        judgingMode: 'points',
      },
    ],
  },
];

export async function runSeedTemplates(onProgress?: (msg: string) => void): Promise<void> {
  for (const template of SEED_TEMPLATES) {
    onProgress?.(`Сеед: "${template.title}"...`);
    await saveTemplate(template);
  }
  onProgress?.(`✓ Успешно seed-ирани ${SEED_TEMPLATES.length} шаблони.`);
}

