import { saveTemplate } from './storage';
import { collection, getDocs, deleteDoc, doc } from 'firebase/firestore';
import { db } from './firebase';
import type { Template } from 'shared';

function uid() {
  try { return crypto.randomUUID(); } catch { return Math.random().toString(36).slice(2); }
}

const NOW = new Date().toISOString();

// Pre-generate IDs needed for cross-referencing in SWITCH conditions (template 5)
const LEKTIRA_SCIENCE_ID  = uid();
const LEKTIRA_ART_ID      = uid();
const LEKTIRA_MISSION_ID  = uid();
const LEKTIRA_SURVEY_ID   = uid();

export const SEED_TEMPLATES: Template[] = [
  // ─── 1. Синтетичка геометрија во реалниот простор ────────────────────────────
  {
    id: 'seed-geometrija-8',
    title: 'Синтетичка геометрија во реалниот простор',
    subject: 'Математика',
    grade: '8 одд.',
    description: 'Учениците наоѓаат агли и пресметуваат симетрали користејќи објекти во природата. Идеално за училишен двор или локален парк.',
    difficulty: 'средно',
    estimatedMinutes: 45,
    playMode: 'singleplayer',
    tags: ['геометрија', 'теренска', 'gps', 'симетрала'],
    stageCount: 5,
    rating: 4.8,
    ratingCount: 12,
    usageCount: 34,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: true,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Добредојдовте на геометриска авантура!',
        description: 'Денес ќе ги истражувате **геометриски форми во реалниот свет**. Ќе конструирате симетрали и ќе докажете дека секоја точка на симетрала е подеднакво оддалечена од краците на аголот.\n\n📐 Подготви: јаже, креда, линијар.\n\nПресретнуваме на GPS точка 1!',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 1, points: 50,
        title: 'Најди ја почетната точка',
        description: 'Оди до аголот кај влезот на зградата (или средиштето на дворот). Кога ќе се наоѓаш на 5 метри, доаѓаш до следниот чекор.',
        targetCoordinates: { latitude: 41.9981, longitude: 21.4254 },
        radiusMeters: 15,
        showMode: 'map',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'MISSION', order: 2, points: 100,
        title: 'Конструирај симетрала',
        description: 'Користејќи јаже или креда, конструирај ја симетралата на аголот кој го формираат две патеки/ѕидови пред тебе.\n\n📸 Сними фотографија од конструкцијата. Мора да се гледаат и двата крака на аголот и симетралата.',
        submissionType: 'photo',
      },
      {
        id: uid(), type: 'QUIZ', order: 3, points: 80,
        title: 'Доказ за симетрала',
        description: 'Земи две точки на различни краци на аголот, подеднакво оддалечени од темето. Измери ги нивните растојанија до симетралата. Колку се тие растојанија?',
        questionType: 'multiple_choice',
        options: ['Нееднакви', 'Подеднакви', 'Зависи од аголот', 'Не може да се измери'],
        correctAnswer: 'Подеднакви',
        hintText: 'Симетралата е "огледало" — секоја точка на неа е на исто растојание од двата крака.',
        requiredToAdvance: false,
        timeLimitSeconds: 60,
      },
      {
        id: uid(), type: 'SURVEY', order: 4, points: 20,
        title: 'Рефлексија',
        description: 'Размисли за денешната активност:',
        surveyQuestions: [
          'Кое беше најтешкото нешто при конструирањето на симетралата?',
          'Дали ти беше полесно да го разбереш концептот со практична вежба наместо на хартија? Зошто?',
          'Каде во секојдневниот живот среќаваш симетрали?',
        ],
      },
    ],
  },

  // ─── 2. Процентополис — QR Квест ─────────────────────────────────────────────
  {
    id: 'seed-procentopolis-7',
    title: 'Процентополис — QR Авантура',
    subject: 'Математика',
    grade: '7 одд.',
    description: 'Мрежа од скриени QR кодови низ училиштето. Секој код активира задача за математичко моделирање и проценти.',
    difficulty: 'средно',
    estimatedMinutes: 50,
    playMode: 'singleplayer',
    tags: ['проценти', 'qr', 'моделирање', 'училиште'],
    stageCount: 6,
    rating: 4.9,
    ratingCount: 18,
    usageCount: 67,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: true,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Добредојдовте во Процентополис!',
        description: '🏙️ Градот Процентополис е полн со математички загатки скриени зад QR кодови.\n\nТвојата задача: Скенирај ги QR кодовите поставени низ училишниот ходник и реши ги задачите за проценти.\n\n**Правила:**\n- Скенирај секој QR код со камерата\n- Одговори точно за да ги освоиш поените\n- Времето е ограничено на 30 секунди по задача!',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'SCAN_CODE', order: 1, points: 50,
        title: 'QR Станица 1 — Влез во градот',
        description: 'Пронајди го QR кодот залепен на влезните врати или огласната табла. Скенирај го за да влезеш во Процентополис!',
        targetQrPayload: 'PROCESNTOPOLIS_STATION_1',
      },
      {
        id: uid(), type: 'QUIZ', order: 2, points: 100,
        title: 'Задача: Попуст во продавница',
        description: 'Кај влезот скенираш информација: **"Продавница нуди 25% попуст на цена од 1200 ден."**\n\nКолку денари изнесува попустот?',
        questionType: 'free_text',
        correctAnswer: '300',
        hintText: 'Процент × Основа ÷ 100 = ?',
        timeLimitSeconds: 30,
        requiredToAdvance: false,
      },
      {
        id: uid(), type: 'SCAN_CODE', order: 3, points: 50,
        title: 'QR Станица 2 — Банка на Процентополис',
        description: 'Пронајди го вториот QR код залепен кај скалите или во ходникот. Во банката чека нова задача!',
        targetQrPayload: 'PROCESNTOPOLIS_STATION_2',
      },
      {
        id: uid(), type: 'QUIZ', order: 4, points: 120,
        title: 'Задача: Банкарска камата',
        description: '🏦 Наклонот на скалите во банката е 35°. Стандардот за пристапност бара наклон **помал од 30°**.\n\nЗа колку проценти треба да се намали наклонот за да ги исполни стандардите?\n\nОдговори со број (без % знак).',
        questionType: 'estimate_number',
        correctAnswer: 5,
        hintText: 'Разлика = 35 - 30 = ? Изрази ја разликата во однос на 35.',
        timeLimitSeconds: 45,
        requiredToAdvance: false,
      },
      {
        id: uid(), type: 'MISSION', order: 5, points: 80,
        title: 'Финален доказ',
        description: '📸 Направи слика на некоја цена или процент кој го гледаш во или околу училиштето (огласна табла, книга, реклама).\n\nСнимката е твојот излез од Процентополис!',
        submissionType: 'photo',
      },
    ],
  },

  // ─── 3. Лов на екосистеми — Биологија ────────────────────────────────────────
  {
    id: 'seed-ekosistemi-6',
    title: 'Лов на екосистеми — Биологија',
    subject: 'Природни науки',
    grade: '6 одд.',
    description: 'Теренска настава. Учениците истражуваат локални екосистеми, фотографираат растенија и мерат податоци на терен.',
    difficulty: 'лесно',
    estimatedMinutes: 60,
    playMode: 'singleplayer',
    tags: ['биологија', 'екосистем', 'теренска', 'природа'],
    stageCount: 6,
    rating: 4.7,
    ratingCount: 9,
    usageCount: 28,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: false,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Денес сте истражувачи!',
        description: '🌿 Добредојдовте на теренска настава по биологија!\n\nДенес ќе ги истражувате **локалните екосистеми** — ќе фотографирате растенија, ќе набљудувате животни и ќе мерите услови на средина.\n\nПодгответе: фотоапарат (телефон), тетратка за набљудувања.\n\n**Бидете внимателни кон природата!** 🍃',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 1, points: 50,
        title: 'Точка 1: Влез во екосистемот',
        description: 'Одете до зеленото подрачје (парк, двор, природа). Овде почнува истражувањето.',
        targetCoordinates: { latitude: 41.9981, longitude: 21.4254 },
        radiusMeters: 20,
        showMode: 'map',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'MISSION', order: 2, points: 100,
        title: 'Фотографирај растение',
        description: '📸 Пронајди растение и направи детална слика.\n\nВо описот наведи:\n- Вид (ако го знаеш)\n- Каде расте (сенка/сонце, влажно/суво)\n- Дали гледаш некои животни или инсекти на него?',
        submissionType: 'photo',
      },
      {
        id: uid(), type: 'QUIZ', order: 3, points: 80,
        title: 'Кој е производител во екосистемот?',
        description: 'Врз основа на тоа што го гледаш наоколу — кој организам е **производител** (прима енергија директно од сонцето)?',
        questionType: 'multiple_choice',
        options: ['Трева и дрвја', 'Лисици и зајаци', 'Глувци и инсекти', 'Габи и бактерии'],
        correctAnswer: 'Трева и дрвја',
        hintText: 'Производителите прават храна преку фотосинтеза — потребно им е сонце!',
        requiredToAdvance: false,
        timeLimitSeconds: 45,
      },
      {
        id: uid(), type: 'MISSION', order: 4, points: 80,
        title: 'Измери ги условите',
        description: '🌡️ Измери ги следните параметри на местото каде се наоѓаш и напиши ги:\n\n- Приближна температура (°C)\n- Влажност (суво / умерено / влажно)\n- Осветленост (сенка / полусенка / директно сонце)\n\nСними аудио запис со твоите набљудувања.',
        submissionType: 'audio',
      },
      {
        id: uid(), type: 'SURVEY', order: 5, points: 20,
        title: 'Набљудувања на теренот',
        description: 'Запиши ги своите теренски набљудувања:',
        surveyQuestions: [
          'Колку различни видови растенија набројуваш (приближно)?',
          'Дали забележа некои животни или инсекти? Кои?',
          'Кои човечки активности ги гледаш кои влијаат на овој екосистем?',
          'Дали мислиш дека овој екосистем е здрав? Зошто?',
        ],
      },
    ],
  },

  // ─── 4. Дигитален Времеплов — Историја ───────────────────────────────────────
  {
    id: 'seed-vremeplov-9',
    title: 'Дигитален Времеплов — Историја',
    subject: 'Историја',
    grade: '9 одд.',
    description: 'Рута низ градот до споменици со аудио-информации. Учениците снимаат видео репортажи како новинари од минатото.',
    difficulty: 'средно',
    estimatedMinutes: 75,
    playMode: 'singleplayer',
    tags: ['историја', 'grad', 'gps', 'споменици', 'новинарство'],
    stageCount: 5,
    rating: 5.0,
    ratingCount: 6,
    usageCount: 15,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: true,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Добредојдовте во Дигиталниот Времеплов!',
        description: '📡 Вие сте **новинари кои известуваат во живо** од историски настани!\n\nДенешната рута ве носи до важни историски места во градот. На секое место ќе добиете кратка историска информација, а потоа ќе снимите **видео репортажа** — глумете дека сте новинари кои известуваат директно од минатото!\n\n🎥 Подгответе камера. Историјата чека!',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 1, points: 50,
        title: 'Историска локација 1',
        description: 'Одете до прва историска точка во градот (централен плоштад или споменик). GPS ќе ве води.',
        targetCoordinates: { latitude: 41.9961, longitude: 21.4316 },
        radiusMeters: 25,
        showMode: 'map',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'MISSION', order: 2, points: 120,
        title: 'Репортажа 1: Историски настан',
        description: '🎙️ Снимете кратка **видео репортажа до 60 секунди** во која:\n\n1. Претставете се како новинар (измислено историско медиумско куќа)\n2. Опишете каде се наоѓате и кој историски настан се случил тука\n3. Кажете зошто е ова место важно за историјата на Македонија\n\nБидете креативни — историјата е жива!',
        submissionType: 'video',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 3, points: 50,
        title: 'Историска локација 2',
        description: 'Продолжете до втората историска точка. Нова приказна чека!',
        targetCoordinates: { latitude: 41.9970, longitude: 21.4283 },
        radiusMeters: 25,
        showMode: 'map',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'QUIZ', order: 4, points: 100,
        title: 'Историски факт — провери го знаењето',
        description: 'Врз основа на сè што научивте денес на теренот:\n\nКоја е улогата на **материјалното наследство** (споменици, градби) во зачувувањето на историската меморија?',
        questionType: 'multiple_choice',
        options: [
          'Служи само за туристички цели',
          'Ги поврзува генерациите и ја чува колективната меморија',
          'Нема практична вредност во модерно доба',
          'Важно е само за историчари',
        ],
        correctAnswer: 'Ги поврзува генерациите и ја чува колективната меморија',
        timeLimitSeconds: 60,
        requiredToAdvance: false,
      },
    ],
  },

  // ─── 5. Интерактивна Лектира — Storytelling со SWITCH ───────────────────────
  {
    id: 'seed-lektira-79',
    title: 'Интерактивна Лектира — Раскажувај приказна!',
    subject: 'Јазици',
    grade: '7-9 одд.',
    description: 'Секоја станица е поглавје. Учениците одговараат на прашања и самите одлучуваат како завршува приказната преку логички разгранувања.',
    difficulty: 'лесно',
    estimatedMinutes: 40,
    playMode: 'singleplayer',
    tags: ['литература', 'storytelling', 'разгранување', 'лектира'],
    stageCount: 7,
    rating: 4.6,
    ratingCount: 14,
    usageCount: 42,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: false,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Поглавје 1: Почетокот',
        description: '📖 *Беше еднаш еден млад студент кој открил тајна библиотека скриена длабоко под градот...*\n\nВо библиотеката имало две врати:\n- **Лева врата**: водела до Сала на науките\n- **Десна врата**: водела до Сала на уметноста\n\nНо за да избере, прво морал да одговори на прашањата на чуварот...',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'QUIZ', order: 1, points: 80,
        title: 'Прашање на чуварот',
        description: 'Чуварот на библиотеката прашува:\n\n*"Која фигура на зборот се користи кога кажуваме: Времето лета?"*',
        questionType: 'multiple_choice',
        options: ['Метафора', 'Персонификација', 'Компарација', 'Хипербола'],
        correctAnswer: 'Метафора',
        hintText: 'Времето не може буквално да лета — претставуваме апстрактно преку конкретно.',
        timeLimitSeconds: 60,
        requiredToAdvance: false,
      },
      {
        id: uid(), type: 'SWITCH', order: 2, points: 0,
        title: 'Чуварот те насочува...',
        description: 'Врз основа на твоите поени, чуварот те насочува кон соодветната сала.',
        conditions: [
          {
            id: uid(),
            label: 'Точен одговор (≥80 поени) → Сала на науките',
            minPoints: 80,
            targetStageId: LEKTIRA_SCIENCE_ID,
          },
        ],
        defaultTargetStageId: LEKTIRA_ART_ID,
        showPathsToPlayer: false,
      },
      {
        id: LEKTIRA_SCIENCE_ID, type: 'INFO', order: 3, points: 0,
        title: 'Сала на науките',
        description: '🔬 *Студентот влегол во Сала на науките. Полиците беа полни со книги за физика, хемија и математика. На средниот стол лежела отворена книга со чудни равенки...*\n\nАко одговориш точно на следното прашање, ќе ја открие тајната на библиотеката!',
        mediaType: 'none',
      },
      {
        id: LEKTIRA_ART_ID, type: 'INFO', order: 4, points: 0,
        title: 'Сала на уметноста',
        description: '🎨 *Студентот влегол во Сала на уметноста. Ѕидовите беа покриени со слики и скулптури. На центарот стоела мистериозна статуа...*\n\nАко одговориш точно на следното прашање, ќе ја открие тајната на библиотеката!',
        mediaType: 'none',
      },
      {
        id: LEKTIRA_MISSION_ID, type: 'MISSION', order: 5, points: 100,
        title: 'Напиши го крајот на приказната',
        description: '✍️ Сега ТИ си авторот!\n\nНапиши краток крај на приказната за студентот (5-7 реченици). Вклучи:\n- Каква тајна открил?\n- Kako се чувствувал?\n- Дали се вратил повторно?\n\nСними аудио запис во кој ја читаш приказната со емоции.',
        submissionType: 'audio',
      },
      {
        id: LEKTIRA_SURVEY_ID, type: 'SURVEY', order: 6, points: 20,
        title: 'Рефлексија за приказната',
        description: 'Размисли за денешната активност:',
        surveyQuestions: [
          'Кој дел од приказната ти беше најинтересен и зошто?',
          'Дали сакаш да читаш книги со разгранување каде сам го бираш крајот?',
          'Кој книжевен лик (реален или измислен) би го поканил во оваа библиотека?',
        ],
      },
    ],
  },

  // ─── 6. Ориентационо трчање и здравје ────────────────────────────────────────
  {
    id: 'seed-orientacisko',
    title: 'Ориентационо трчање и здравје',
    subject: 'Физичко',
    grade: 'Сите',
    description: 'Комбинира физичка активност и знаење. Спринт помеѓу GPS точки и одговарање на брз квиз за анатомија и здравје.',
    difficulty: 'лесно',
    estimatedMinutes: 35,
    playMode: 'singleplayer',
    tags: ['физичко', 'трчање', 'gps', 'здравје', 'анатомија'],
    stageCount: 7,
    rating: 4.5,
    ratingCount: 11,
    usageCount: 51,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: false,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Спремни, внимание, крени!',
        description: '🏃 Добредојдовте на **Ориентационото трчање**!\n\nПравила:\n1. Трчај до секоја GPS точка\n2. Кога ќе пристигнеш, одговори на брз квиз\n3. Помалку време = повеќе поени\n4. Нема правилен одговор за здравје — сите тела се различни!\n\n🎯 Цел: Движење + Знаење = Здравје!\n\nГотов? Поаѓај!',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 1, points: 50,
        title: '🏁 Точка 1: Загревање',
        description: 'Трчај до ознаката А (северен агол на теренот/дворот). Загрејте се!',
        targetCoordinates: { latitude: 41.9985, longitude: 21.4260 },
        radiusMeters: 10,
        showMode: 'arrow',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'QUIZ', order: 2, points: 100,
        title: 'Квиз: Срце и крвоток',
        description: '❤️ Брзо! Колку пати во минута чука срцето на здрав возрасен во мирување?',
        questionType: 'multiple_choice',
        options: ['20-40 пати', '60-100 пати', '120-160 пати', '160-200 пати'],
        correctAnswer: '60-100 пати',
        timeLimitSeconds: 20,
        requiredToAdvance: false,
        hintText: 'Пулсот е мерка за здравјето на срцето.',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 3, points: 50,
        title: '🏁 Точка 2: Спринт!',
        description: 'Спринт до ознаката Б (јужен агол)! Пресметај ги кардио поените!',
        targetCoordinates: { latitude: 41.9978, longitude: 21.4268 },
        radiusMeters: 10,
        showMode: 'arrow',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'QUIZ', order: 4, points: 100,
        title: 'Квиз: Мускули и коски',
        description: '💪 Колку коски има во човечкото тело на возрасен?',
        questionType: 'multiple_choice',
        options: ['106', '206', '306', '406'],
        correctAnswer: '206',
        timeLimitSeconds: 20,
        requiredToAdvance: false,
        hintText: 'Новородените имаат повеќе — со растење некои коски се спојуваат.',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 5, points: 50,
        title: '🏁 Точка 3: Финален спринт!',
        description: 'Последна точка — дај сè! Трчај до ознаката В (старт)!',
        targetCoordinates: { latitude: 41.9981, longitude: 21.4254 },
        radiusMeters: 10,
        showMode: 'arrow',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'TOURNAMENT', order: 6, points: 150,
        title: '🏆 Финален турнир: Класна битка!',
        description: 'Споредете ги резултатите со соучениците. Кој е најбрз ориентирист со најдобро знаење за здравје?\n\nЧеститки на сите учесници — движењето е победа!',
        teamCount: 4,
        taskDescription: 'Кој тим освоил највеќе поени вкупно?',
        judgingMode: 'points',
      },
    ],
  },

  // ─── 7. Камен Мост — QR Историска Авантура (демо за QR_TASK) ─────────────────
  {
    id: 'seed-kamen-most',
    title: 'Камен Мост — QR Историска Авантура',
    subject: 'Историја',
    grade: '8-9 одд.',
    description: 'Скенирај QR кодови поставени кај историски точки и одговори на задачите директно во апликацијата. Совршено за обиколка на стариот дел од градот.',
    difficulty: 'средно',
    estimatedMinutes: 55,
    playMode: 'singleplayer',
    tags: ['историја', 'qr', 'култура', 'скопје', 'обиколка'],
    stageCount: 5,
    rating: 4.9,
    ratingCount: 7,
    usageCount: 19,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: true,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Добредојдовте на QR Историската тура!',
        description: '🏛️ Денес истражувате историски бисери преку **QR кодови**.\n\nНа секоја точка ќе најдете QR код залепен од наставникот. Скенирајте го со камерата — ќе ви се открие задача на која одговарате веднаш во апликацијата.\n\n📱 Подгответе го телефонот. Историјата е на еден скен растојание!',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'QR_TASK', order: 1, points: 100,
        title: 'Станица 1 — Камен Мост',
        description: 'Пронајди го QR кодот залепен кај Камен Мост (или на таблата што наставникот ја постави). Скенирај го!',
        targetQrPayload: 'KAMEN_MOST_001',
        taskTitle: 'Историја на Камен Мост',
        taskDescription: 'Камен Мост е симбол на Скопје и го поврзува двата брега на реката што минува низ градот.\n\n**Како се вика реката над која се протега Камен Мост?**',
        answerType: 'text',
        correctAnswer: 'Вардар',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'QR_TASK', order: 2, points: 120,
        title: 'Станица 2 — Старата Чаршија',
        description: 'Премини во Старата Чаршија и најди го вториот QR код. Скенирај за да ја откриеш задачата.',
        targetQrPayload: 'CARSIJA_002',
        taskTitle: 'Занаети во Чаршијата',
        taskDescription: 'Старата Скопска Чаршија со векови е центар на трговијата и занаетите.\n\n**Кој од следните занаети е традиционално поврзан со чаршијата?**',
        answerType: 'multiple_choice',
        options: ['Филигран (изработка на накит)', 'Програмирање', 'Авто-механика', 'Фотографија со дрон'],
        correctAnswer: 'Филигран (изработка на накит)',
        requiredToAdvance: false,
      },
      {
        id: uid(), type: 'QR_TASK', order: 3, points: 100,
        title: 'Станица 3 — Тврдина Кале',
        description: 'Искачи се до Тврдината Кале и скенирај го третиот QR код.',
        targetQrPayload: 'KALE_003',
        taskTitle: 'Фото-доказ од Кале',
        taskDescription: '📸 Од ѕидините на Кале се гледа панорама на целиот град.\n\n**Направи фотографија на еден историски објект или панорама што го гледаш од тука.** Опиши накратко што претставува.',
        answerType: 'photo',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'SURVEY', order: 4, points: 20,
        title: 'Рефлексија на турата',
        description: 'Сподели ги твоите впечатоци од QR историската авантура:',
        surveyQuestions: [
          'Која станица ти беше најинтересна и зошто?',
          'Што ново научи за историјата на твојот град?',
          'Дали скенирањето QR кодови ја направи наставата позабавна?',
        ],
      },
    ],
  },

  // ─── 8. Бои и Емоции — Уметничка Авантура ────────────────────────────────────
  {
    id: 'seed-boi-emocii',
    title: 'Бои и Емоции — Уметничка Авантура',
    subject: 'Уметност',
    grade: '5-7 одд.',
    description: 'Учениците истражуваат теорија на бои, набљудуваат уметност во околината и креираат сопствено дело. Комбинација на QR задачи и фото-мисии.',
    difficulty: 'лесно',
    estimatedMinutes: 45,
    playMode: 'singleplayer',
    tags: ['уметност', 'бои', 'емоции', 'креативност', 'qr'],
    stageCount: 5,
    rating: 4.7,
    ratingCount: 5,
    usageCount: 12,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: false,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Светот низ боите',
        description: '🎨 Боите се секаде околу нас и тие будат емоции!\n\nДенес ќе истражуваш како боите се мешаат, што значат и како уметниците ги користат. Подгответе: блок за цртање, боички или маркери.\n\nДа почнеме со малку теорија на бои!',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'QR_TASK', order: 1, points: 100,
        title: 'QR Палета — основни бои',
        description: 'Скенирај го QR кодот кај уметничкиот кат / огласна табла за да добиеш задача за бои.',
        targetQrPayload: 'ART_COLORS_001',
        taskTitle: 'Мешање на бои',
        taskDescription: 'Кога ќе ги измешаме **жолтата** и **сината** боја, која боја добиваме?',
        answerType: 'multiple_choice',
        options: ['Зелена', 'Портокалова', 'Виолетова', 'Кафена'],
        correctAnswer: 'Зелена',
        requiredToAdvance: false,
      },
      {
        id: uid(), type: 'MISSION', order: 2, points: 100,
        title: 'Лов на бои во природа',
        description: '📸 Прошетај наоколу и пронајди три предмети со различни бои (на пр. зелено лисје, црвен ѕид, сина табла).\n\nНаправи фотографија на која се гледаат сите три бои.',
        submissionType: 'photo',
      },
      {
        id: uid(), type: 'QR_TASK', order: 3, points: 120,
        title: 'QR Ателье — твое дело',
        description: 'Скенирај го финалниот QR код во ателјето за креативната задача.',
        targetQrPayload: 'ART_CREATE_002',
        taskTitle: 'Нацртај ја својата емоција',
        taskDescription: '🖌️ Размисли како се чувствуваш денес. Избери бои што ја претставуваат таа емоција и нацртај мала апстрактна слика.\n\n📸 Сликај го твоето дело и прикачи го.',
        answerType: 'photo',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'SURVEY', order: 4, points: 20,
        title: 'Бои и чувства',
        description: 'Размисли за врската меѓу боите и емоциите:',
        surveyQuestions: [
          'Која боја ја избра за твојата емоција и зошто?',
          'Која боја те смирува, а која те разбудува?',
          'Дали забележа дека различни луѓе поврзуваат различни емоции со иста боја?',
        ],
      },
    ],
  },

  // ─── 9. Тајните на Водата — Хемија ───────────────────────────────────────────
  {
    id: 'seed-voda-hemija',
    title: 'Тајните на Водата — Хемија',
    subject: 'Природни науки',
    grade: '7-8 одд.',
    description: 'Истражувачка авантура за молекулата на водата, нејзините состојби и значење. QR станици со задачи плус практична мисија.',
    difficulty: 'средно',
    estimatedMinutes: 50,
    playMode: 'singleplayer',
    tags: ['хемија', 'вода', 'молекули', 'природни науки', 'qr'],
    stageCount: 6,
    rating: 4.8,
    ratingCount: 6,
    usageCount: 14,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: false,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Капка по капка — мисија вода',
        description: '💧 Водата е најважната супстанца за животот!\n\nДенес ќе ги откриеме нејзините тајни: од што е составена, во кои состојби постои и зошто е толку посебна. Скенирај ги QR станиците и реши ги задачите.',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'QR_TASK', order: 1, points: 100,
        title: 'QR Станица 1 — Формула',
        description: 'Скенирај го првиот QR код во лабораторијата / училницата.',
        targetQrPayload: 'WATER_FORMULA_001',
        taskTitle: 'Хемиска формула на водата',
        taskDescription: 'Молекулата на водата е составена од два атома водород и еден атом кислород.\n\n**Напиши ја хемиската формула на водата** (на пр. формат: H2O).',
        answerType: 'text',
        correctAnswer: 'H2O',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'QUIZ', order: 2, points: 80,
        title: 'Квиз: Колку атоми?',
        description: 'Колку атоми вкупно има во една молекула вода (H₂O)?',
        questionType: 'estimate_number',
        correctAnswer: 3,
        hintText: 'Изброј: 2 водород + 1 кислород.',
        timeLimitSeconds: 30,
        requiredToAdvance: false,
      },
      {
        id: uid(), type: 'QR_TASK', order: 3, points: 120,
        title: 'QR Станица 2 — Состојби',
        description: 'Пронајди го вториот QR код кај прозорецот / чешмата и скенирај.',
        targetQrPayload: 'WATER_STATES_002',
        taskTitle: 'Состојби на водата',
        taskDescription: 'Водата може да се појави во три агрегатни состојби.\n\n**Како се вика преминот на водата од течна во гасовита состојба?**',
        answerType: 'multiple_choice',
        options: ['Испарување', 'Замрзнување', 'Топење', 'Кондензација'],
        correctAnswer: 'Испарување',
        requiredToAdvance: false,
      },
      {
        id: uid(), type: 'MISSION', order: 4, points: 100,
        title: 'Пронајди ја водата',
        description: '📸 Направи фотографија на вода во некоја од нејзините состојби околу тебе (течна вода, мраз, пареа, роса...).\n\nОпиши во која состојба е и зошто.',
        submissionType: 'photo',
      },
      {
        id: uid(), type: 'SURVEY', order: 5, points: 20,
        title: 'Размислување за водата',
        description: 'Заврши ја авантурата со неколку размислувања:',
        surveyQuestions: [
          'Зошто водата е толку важна за живите организми?',
          'Како можеме да ја штедиме водата во секојдневниот живот?',
          'Што ново научи за состојбите на водата?',
        ],
      },
    ],
  },

  // ─── 10. Скопје низ вековите — Туристичка тура ───────────────────────────────
  {
    id: 'seed-skopje-tura',
    title: 'Скопје низ вековите — Туристичка тура',
    subject: 'Историја',
    grade: 'Сите',
    description: 'Водена прошетка низ старото градско јадро на Скопје. Идеална за туристички агенции, екскурзии и семејства — открива знаменитости преку GPS точки и QR станици.',
    difficulty: 'лесно',
    estimatedMinutes: 75,
    playMode: 'singleplayer',
    tags: ['туризам', 'скопје', 'историја', 'екскурзија', 'gps', 'qr'],
    stageCount: 6,
    rating: 4.9,
    ratingCount: 21,
    usageCount: 88,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: true,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Добредојдовте во Скопје!',
        description: '🏛️ Започнуваме незаборавна прошетка низ историјата на главниот град.\n\nЌе поминеме покрај Камен Мост, Старата чаршија и Калето. На секоја станица ве чека задача.\n\n👟 Подгответе удобни чевли и полна батерија — авантурата трае околу 75 минути.',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 1, points: 50,
        title: 'Камен Мост',
        description: 'Упатете се кон **Камен Мост** — симболот на градот што го поврзува плоштадот со Старата чаршија. Кога ќе застанете на средината на мостот, продолжете.',
        targetCoordinates: { latitude: 41.9962, longitude: 21.4318 },
        radiusMeters: 25,
        showMode: 'map',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'QR_TASK', order: 2, points: 100,
        title: 'QR Станица — Старата чаршија',
        description: 'Влезете во Старата чаршија и пронајдете го QR кодот залепен кај информативната табла на влезот.',
        targetQrPayload: 'SKOPJE_CARSIJA_001',
        taskTitle: 'Срцето на старото Скопје',
        taskDescription: 'Старата скопска чаршија е една од најголемите на Балканот.\n\n**Од кој историски период потекнува чаршијата?**',
        answerType: 'multiple_choice',
        options: ['Римско време', 'Османлиско време', 'Византиско време', 'Современо доба'],
        correctAnswer: 'Османлиско време',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'QUIZ', order: 3, points: 80,
        title: 'Тврдината Кале',
        description: 'Погледнете нагоре кон тврдината **Кале**, која доминира над градот. На кој хидрографски објект е изградена таа за да го штити градот?',
        questionType: 'multiple_choice',
        options: ['Реката Вардар', 'Охридско Езеро', 'Реката Треска', 'Морето'],
        correctAnswer: 'Реката Вардар',
        hintText: 'Истата река тече под Камен Мост.',
        requiredToAdvance: false,
        timeLimitSeconds: 45,
      },
      {
        id: uid(), type: 'MISSION', order: 4, points: 100,
        title: 'Фотографирај го твоето Скопје',
        description: '📸 Направете една фотографија од омилената знаменитост што ја видовте денес.\n\nНека биде кадар достоен за разгледница!',
        submissionType: 'photo',
      },
      {
        id: uid(), type: 'SURVEY', order: 5, points: 20,
        title: 'Впечатоци од турата',
        description: 'Поделете ги вашите впечатоци:',
        surveyQuestions: [
          'Која знаменитост ви остави најголем впечаток?',
          'Дали научивте нешто ново за историјата на Скопје?',
          'Дали би ја препорачале оваа тура на пријател?',
        ],
      },
    ],
  },

  // ─── 11. City Quest — English in the City (Јазици) ───────────────────────────
  {
    id: 'seed-angliski-grad',
    title: 'City Quest — Англиски низ градот',
    subject: 'Јазици',
    grade: '6-8 одд.',
    description: 'Забавна авантура за вежбање англиски вокабулар на отворено. Учениците читаат натписи, бараат предмети и одговараат на англиски.',
    difficulty: 'средно',
    estimatedMinutes: 40,
    playMode: 'singleplayer',
    tags: ['англиски', 'вокабулар', 'јазици', 'теренска', 'qr'],
    stageCount: 5,
    rating: 4.7,
    ratingCount: 9,
    usageCount: 27,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: false,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Welcome to the City Quest!',
        description: '🇬🇧 Today you become a word detective!\n\nYou will explore your surroundings and answer in **English**. Read the signs around you and have fun.\n\nLet\'s start! 🚀',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'QUIZ', order: 1, points: 80,
        title: 'Find the colours',
        description: 'Погледнете околу себе. **What colour is the sky right now?** Напишете го одговорот на англиски.',
        questionType: 'free_text',
        correctAnswer: 'blue',
        hintText: 'On a clear day it is "blue".',
        requiredToAdvance: false,
      },
      {
        id: uid(), type: 'QR_TASK', order: 2, points: 100,
        title: 'QR Station — Shopping words',
        description: 'Find the QR code near the shop / school entrance and scan it.',
        targetQrPayload: 'ENGLISH_SHOP_001',
        taskTitle: 'At the shop',
        taskDescription: 'You want to buy something to read.\n\n**What is the English word for a place where you buy books?**',
        answerType: 'multiple_choice',
        options: ['Bakery', 'Bookshop', 'Pharmacy', 'Butcher'],
        correctAnswer: 'Bookshop',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'MISSION', order: 3, points: 100,
        title: 'Spell it with objects',
        description: '📸 Find objects around you whose English names start with the letters **C - A - T**.\n\nTake a photo of all three together (e.g. Car, Apple, Tree).',
        submissionType: 'photo',
      },
      {
        id: uid(), type: 'SURVEY', order: 4, points: 20,
        title: 'Reflection',
        description: 'Think about today\'s quest:',
        surveyQuestions: [
          'Which new English word did you learn today?',
          'Was it easier to remember words outside the classroom?',
          'Which task was the most fun?',
        ],
      },
    ],
  },

  // ─── 12. Дрвја и растенија во паркот (Природни науки / Биологија) ─────────────
  {
    id: 'seed-biologija-park',
    title: 'Дрвја и растенија во паркот',
    subject: 'Природни науки',
    grade: '5-6 одд.',
    description: 'Истражувачка авантура на отворено за препознавање дрвја, листови и растенија. Поттикнува љубов кон природата и набљудување.',
    difficulty: 'лесно',
    estimatedMinutes: 45,
    playMode: 'singleplayer',
    tags: ['биологија', 'природа', 'растенија', 'парк', 'екологија'],
    stageCount: 5,
    rating: 4.8,
    ratingCount: 11,
    usageCount: 31,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: false,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Мали природонаучници',
        description: '🌳 Денес паркот е наша лабораторија!\n\nЌе набљудуваме дрвја, листови и тревки, и ќе откриеме како растенијата дишат и растат.\n\n🔍 Отворете ги очите и започнете да истражувате!',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'MISSION', order: 1, points: 100,
        title: 'Колекција на листови',
        description: '🍃 Пронајдете три различни видови листови (различни форми).\n\n📸 Подредете ги еден до друг и фотографирајте ги.',
        submissionType: 'photo',
      },
      {
        id: uid(), type: 'QUIZ', order: 2, points: 80,
        title: 'Како дишат растенијата?',
        description: 'Растенијата „дишат" преку ситни отвори на листовите. Кој гас го испуштаат растенијата дење, а ни е неопходен за живот?',
        questionType: 'multiple_choice',
        options: ['Јаглерод диоксид', 'Кислород', 'Азот', 'Водена пареа'],
        correctAnswer: 'Кислород',
        hintText: 'Истиот гас што ние го вдишуваме.',
        requiredToAdvance: false,
        timeLimitSeconds: 45,
      },
      {
        id: uid(), type: 'QR_TASK', order: 3, points: 100,
        title: 'QR Станица — Делови на растението',
        description: 'Пронајдете го QR кодот кај информативната табла во паркот и скенирајте го.',
        targetQrPayload: 'BIO_PLANT_001',
        taskTitle: 'Кореновиот систем',
        taskDescription: 'Секое растение има дел кој го држи во земјата и ги црпи водата и хранливите материи.\n\n**Како се вика тој дел на растението?**',
        answerType: 'text',
        correctAnswer: 'корен',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'SURVEY', order: 4, points: 20,
        title: 'Размислување за природата',
        description: 'Заврши со размислување:',
        surveyQuestions: [
          'Кое растение или дрво ти беше најинтересно денес?',
          'Зошто е важно да ги чуваме зелените површини?',
          'Што ново научи за тоа како растат растенијата?',
        ],
      },
    ],
  },

  // ─── 13. Физика на игралиштето (Природни науки / Физика) ─────────────────────
  {
    id: 'seed-fizika-igraliste',
    title: 'Физика на игралиштето',
    subject: 'Природни науки',
    grade: '7-8 одд.',
    description: 'Учениците ги откриваат законите на физиката преку лулашки, тобогани и вртелешки. Сила, гравитација и движење — во акција!',
    difficulty: 'средно',
    estimatedMinutes: 45,
    playMode: 'singleplayer',
    tags: ['физика', 'сила', 'гравитација', 'движење', 'игралиште'],
    stageCount: 5,
    rating: 4.9,
    ratingCount: 8,
    usageCount: 19,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: false,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Игралиштето е лабораторија',
        description: '⚙️ Секоја лулашка, тобоган и вртелешка крие физика!\n\nДенес ќе ги откриеме гравитацијата, силата на триење и претворањето на енергијата — додека се забавуваме.\n\nДа започнеме! 🛝',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'QUIZ', order: 1, points: 80,
        title: 'Лулашка и нишало',
        description: 'Лулашката се однесува како нишало. Што ќе се случи со времето на едно нишање ако детето седне (центарот на маса се спушти подолу)?',
        questionType: 'multiple_choice',
        options: ['Ќе се нишка побрзо', 'Ќе се нишка побавно', 'Нема да се промени', 'Ќе застане'],
        correctAnswer: 'Ќе се нишка побавно',
        hintText: 'Подолго нишало = подолг период на нишање.',
        requiredToAdvance: false,
        timeLimitSeconds: 60,
      },
      {
        id: uid(), type: 'MISSION', order: 2, points: 100,
        title: 'Тобоган и триење',
        description: '🎥 Снимете кратко видео како предмет (на пр. чанта или другар) се лизга по тобоганот.\n\nНабљудувајте: каде забрзува, а каде успорува поради триење.',
        submissionType: 'video',
      },
      {
        id: uid(), type: 'QR_TASK', order: 3, points: 120,
        title: 'QR Станица — Гравитација',
        description: 'Пронајдете го QR кодот кај вртелешката и скенирајте го.',
        targetQrPayload: 'PHYS_GRAVITY_001',
        taskTitle: 'Слободен пад',
        taskDescription: 'Галилео докажал дека сите тела паѓаат со исто забрзување (ако нема воздушен отпор).\n\n**Колку приближно изнесува гравитациското забрзување на Земјата (m/s²)?**',
        answerType: 'multiple_choice',
        options: ['1.6', '9.8', '20', '100'],
        correctAnswer: '9.8',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'SURVEY', order: 4, points: 20,
        title: 'Физика околу нас',
        description: 'Размисли:',
        surveyQuestions: [
          'Каде на игралиштето ја почувствува силата на гравитацијата најсилно?',
          'Како триењето ни помага, а како ни пречи?',
          'Што ново откри за движењето денес?',
        ],
      },
    ],
  },

  // ─── 14. Авантура во музеј (Уметност) ────────────────────────────────────────
  {
    id: 'seed-muzej-umetnost',
    title: 'Авантура во музеј',
    subject: 'Уметност',
    grade: 'Сите',
    description: 'Интерактивна тура низ музеј или галерија со QR станици кај експонатите. Совршена за училишни посети и туристички групи.',
    difficulty: 'лесно',
    estimatedMinutes: 50,
    playMode: 'singleplayer',
    tags: ['уметност', 'музеј', 'галерија', 'култура', 'туризам', 'qr'],
    stageCount: 5,
    rating: 4.8,
    ratingCount: 7,
    usageCount: 22,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: true,
    isPro: false,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Добредојдовте во музејот',
        description: '🖼️ Музејот е полн со приказни што чекаат да бидат откриени!\n\nСледете ги QR станиците кај експонатите, набљудувајте внимателно и одговарајте на задачите.\n\n🤫 Не заборавајте — во музеј зборуваме тивко!',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'QR_TASK', order: 1, points: 100,
        title: 'QR Станица — Боите на сликата',
        description: 'Пронајдете го QR кодот до првата изложена слика и скенирајте го.',
        targetQrPayload: 'MUSEUM_PAINT_001',
        taskTitle: 'Топли и студени бои',
        taskDescription: 'Уметниците користат бои за да предизвикаат чувства.\n\n**Која од овие бои се смета за „топла" боја?**',
        answerType: 'multiple_choice',
        options: ['Сина', 'Зелена', 'Црвена', 'Виолетова'],
        correctAnswer: 'Црвена',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'MISSION', order: 2, points: 100,
        title: 'Омилен експонат',
        description: '📸 Прошетајте низ една сала и фотографирајте го експонатот што најмногу ви се допадна.\n\n(Проверете дали е дозволено фотографирање!)',
        submissionType: 'photo',
      },
      {
        id: uid(), type: 'QUIZ', order: 3, points: 80,
        title: 'Видови уметност',
        description: 'Уметничко дело создадено со длето од камен или дрво, кое има три димензии, се нарекува:',
        questionType: 'multiple_choice',
        options: ['Слика', 'Скулптура', 'Фотографија', 'Цртеж'],
        correctAnswer: 'Скулптура',
        hintText: 'Можеш да ја обиколиш од сите страни.',
        requiredToAdvance: false,
        timeLimitSeconds: 45,
      },
      {
        id: uid(), type: 'SURVEY', order: 4, points: 20,
        title: 'Впечатоци од музејот',
        description: 'Поделете ги мислите:',
        surveyQuestions: [
          'Кој експонат ве воодушеви најмногу и зошто?',
          'Какво чувство ви предизвикаа боите на омилената слика?',
          'Дали би сакале повторно да посетите музеј?',
        ],
      },
    ],
  },

  // ─── 15. Тимбилдинг авантура за компании (Останато) ──────────────────────────
  {
    id: 'seed-teambuilding-firma',
    title: 'Тимбилдинг авантура за компании',
    subject: 'Останато',
    grade: 'Возрасни',
    description: 'Динамична тимска авантура на отворено за фирми и организации. Соработка, комуникација и забава — идеална за team-building настани.',
    difficulty: 'средно',
    estimatedMinutes: 90,
    playMode: 'multiplayer',
    tags: ['тимбилдинг', 'компании', 'соработка', 'возрасни', 'qr'],
    stageCount: 6,
    rating: 5.0,
    ratingCount: 5,
    usageCount: 16,
    authorId: 'admin',
    authorName: 'Авантура тим',
    status: 'approved',
    isPublic: true,
    isFeatured: true,
    isPro: true,
    createdAt: NOW,
    updatedAt: NOW,
    stages: [
      {
        id: uid(), type: 'INFO', order: 0, points: 0,
        title: 'Добредојдовте, тимови!',
        description: '🤝 Денес не сте колеги — вие сте екипа на авантуристи!\n\nЌе решавате загатки, ќе наоѓате локации и ќе соработувате. Победува тимот со најмногу поени и најдобар тимски дух.\n\nГотови? Да започнеме! 🏁',
        mediaType: 'none',
      },
      {
        id: uid(), type: 'TOURNAMENT', order: 1, points: 0,
        title: 'Формирање тимови',
        description: 'Поделете се во тимови. Секој тим избира име и лидер. Запишете го името кога ќе бидете подготвени.',
        teamCount: 4,
        taskDescription: 'Секој тим смислува име и боен поклич за 5 минути.',
        judgingMode: 'manual',
      },
      {
        id: uid(), type: 'FIND_SPOT', order: 2, points: 80,
        title: 'Прва точка за средба',
        description: 'Сите тимови треба да стигнат до договорената почетна локација. Кога ќе бидете таму, продолжете.',
        targetCoordinates: { latitude: 41.9981, longitude: 21.4254 },
        radiusMeters: 30,
        showMode: 'map',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'QR_TASK', order: 3, points: 120,
        title: 'QR Загатка — Шифра на тимот',
        description: 'Пронајдете го скриениот QR код на локацијата и скенирајте го заедно.',
        targetQrPayload: 'TEAM_RIDDLE_001',
        taskTitle: 'Заедничка одлука',
        taskDescription: 'Загатка: „Растам кога ме делиш, а исчезнувам кога ме кријам. Што сум јас?"\n\n**Договорете се во тимот и впишете го одговорот.**',
        answerType: 'text',
        correctAnswer: 'знаење',
        requiredToAdvance: true,
      },
      {
        id: uid(), type: 'MISSION', order: 4, points: 100,
        title: 'Тимска фотографија',
        description: '📸 Целиот тим креира креативна групна фотографија со договорена поза или формација.\n\nКреативноста носи бонус поени!',
        submissionType: 'photo',
      },
      {
        id: uid(), type: 'SURVEY', order: 5, points: 20,
        title: 'Рефлексија на тимот',
        description: 'Разговарајте и одговорете:',
        surveyQuestions: [
          'Која беше клучната одлука што го зближи тимот?',
          'Кој член се истакна со неочекувана улога?',
          'Што ќе пренесете од оваа авантура на работното место?',
        ],
      },
    ],
  },
];

/**
 * Брише стари дупликати на seed шаблоните што останале од порано
 * (кога ID-то беше случајно генерирано). Ги препознава по наслов:
 * секој документ со наслов на seed-шаблон, но со ID различно од стабилното, се брише.
 */
export async function cleanupDuplicateTemplates(onProgress?: (msg: string) => void): Promise<number> {
  const seedTitleToId = new Map(SEED_TEMPLATES.map(t => [t.title, t.id]));
  const snap = await getDocs(collection(db, 'templates'));
  let deleted = 0;
  for (const d of snap.docs) {
    const data = d.data() as Template;
    const stableId = seedTitleToId.get(data.title);
    if (stableId && d.id !== stableId) {
      onProgress?.(`Бришам дупликат: "${data.title}"`);
      await deleteDoc(doc(db, 'templates', d.id));
      deleted++;
    }
  }
  onProgress?.(deleted > 0 ? `✓ Избришани ${deleted} дупликати.` : '✓ Нема дупликати за бришење.');
  return deleted;
}

export async function runSeedTemplates(onProgress?: (msg: string) => void): Promise<void> {
  for (const template of SEED_TEMPLATES) {
    onProgress?.(`Сеед: "${template.title}"...`);
    await saveTemplate(template);
  }
  onProgress?.(`✓ Успешно seed-ирани ${SEED_TEMPLATES.length} шаблони.`);
}

